version: '3.2'
services:
  main:
    image: nginx
    volumes:
      - './main/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './main/html:/usr/share/nginx/html:ro'
    ports:
      - "8000:80"
  pin:
    build: flask_base/
    volumes:
      - './pin:/home/user/app:ro'
  pin2:
    build: flask_base/
    volumes:
      - './pin2:/home/user/app:ro'
  forum:
    build: flask_base/
    volumes:
      - './forum:/home/user/app:ro'
