version: '3.2'
services:
  main:
    image: nginx
    volumes:
      - source: ./main/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        type: bind
      - source: ./main/html
        target: /usr/share/nginx/html
        read_only: true
        type: bind
    ports:
      - "8000:80"
  pin:
    build: pin
  pin2:
    build: pin2
