version: '3.2'
services:
  main:
    image: nginx
    volumes:
      - './main/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './main/proxy_params:/etc/nginx/proxy_params:ro'
      - './main/html:/usr/share/nginx/html:ro'
    ports:
      - "8000:80"
  pin:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './pin:/home/user/app:ro'
  pin2:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './pin2:/home/user/app:ro'
  forum:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './forum:/home/user/app:ro'
  gallery:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './gallery:/home/user/app:ro'
  name:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './name:/home/user/app:ro'
    entrypoint: ['flask', 'run', '-h', '0.0.0.0', '-p', '8000']
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
  mines:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './mines:/home/user/app:ro'
  forum2:
    build: flask_base/
    volumes:
      - './base_templates/base.html:/home/user/app/templates/base.html:ro'
      - './forum2:/home/user/app:ro'
